name = "prod-denybot"
main = "dist/index.mjs"
compatibility_date = "experimental"
node_compat = true

[[queues.producers]]
queue = "my-queue"
binding = "QUEUE"

[durable_objects]
bindings = [{ name = "pagination", class_name = "Pagination" }]

[build]
command = "node build.js"

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true
