node_compat = true
name = "prod-denybot"
main = "dist/index.mjs"
compatibility_date = "experimental"

[triggers]
crons = ["* * * * *"]

[[queues.producers]]
queue = "my-queue"
binding = "QUEUE"

[[queues.consumers]]
queue = "my-queue"
max_batch_size = 3
max_batch_timeout = 60

[durable_objects]
bindings = [{ name = "DURABLE", class_name = "Pagination" }]

[build]
command = "node build.js"

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true
